development:
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_development_tutors
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_test_tutors
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_production_tutors
  pool: 5
  username:
  password: